### ISSUE TITLE
ReactNative安卓首屏白屏优化问题

### ISSUE THREAD

**Issue by LiushuiXiaoxia** [cnsnake11/blog#19]
你好，看了下『ReactNative安卓首屏白屏优化』，有几个问题需要需要了解下。

1.如果提前初始化ReactRootView，那么ReactRootView里面的Context不会有内存泄露问题吗？
2.如果从缓存中加载ReactRootView，再次进入的时候，虽然可以加快速度，但是界面内容确实固定的，不能刷新的？

**Comment by cnsnake11** [comment]
你好
1. 因为context我们传入的是首页activity，他是app的首页，只要app打开，就一直存在的，所以我们使用他作为context，也并没有多创建什么对象，也并没有发现有内存泄漏的情况。
2. 以前测试的结果我记得页面是刷新的，每次进来都和第一次进来的状态一致。猜测应该是setContentView(mReactRootView);就会从jsbundle的初始化状态开始吧。

**Comment by LiushuiXiaoxia** [comment]
我试了下，如果react native里面是scrollview，比如滚动到底部，那么再次进来的时候，scrollview的位置还是在底部，如果我从natvie界面传入一些参数过来，都没有执行。同样，Compoent中的componentWillUnmount，render也没有再次执行。

**Comment by cnsnake11** [comment]
你好 
你说的问题我在以前测试的时候不太记得了，但我印象中是没这个问题的。。。
我们现在的解决方案，和文章里写的已经不太一样了，并且确实没有你说的这个问题了。
现在的方案是：
1. 缓存mReactInstanceManager，而不是缓存ReactRootView
2. 在app启动时候要缓存mReactInstanceManager，同时要实例化一次ReactRootView【如果不这样做，也可以提速，但不是最快】
3. 每次需要开启reactview的时候，都要new一个ReactRootView，然后传入缓存的mReactInstanceManager即可。【类似这行    mReactRootView.startReactApplication(mReactInstanceManager, getMainComponentName(), getLaunchOptions());
】

**Comment by LiushuiXiaoxia** [comment]
已经试过你说的第二种方法，确实提速不少，多谢。

**Comment by shihpeng** [comment]
Your second approach (new a ReactRootView in application) works like a charm! How do you know that?

**Comment by shihpeng** [comment]
请问一下，关于你提到的第二中方法:

```
2. 在app启动时候要缓存mReactInstanceManager，同时要实例化一次ReactRootView【如果不这样做，也可以提速，但不是最快】
```

其中的`同时要实例化一次ReactRootView`，请问具体做法是怎样的呢？能稍微解说一下吗？
