### ISSUE TITLE
增量更新的图片怎么处理

### ISSUE THREAD

**Issue by xiaxiazhu** [cnsnake11/blog#28]
rt 谢谢谢西

**Comment by xiaxiazhu** [comment]
增量只是打包js bundle ，那assets部分呢？

**Comment by luoyjx** [comment]
md5算法对比

**Comment by cnsnake11** [comment]
您好，如楼上所说，assets部分的文件，会挨个文件进行比对，找出新增和修改过的文件，其中修改过的判断是通过文件的md5进行的。。。增量包中会包含新增和修改过的文件。

**Comment by xiaxiazhu** [comment]
@cnsnake11 @luoyjx  多谢，还有个问题，就是，
![image](https://cloud.githubusercontent.com/assets/4719920/21608742/4f7cd50a-d1f9-11e6-8c4d-c9a95108c0f8.png)
我们的打包出来的bundle文件夹里面是src目录里面有images这些文件。 codepush 推送的bundle.js 里面就会有这些文件的base64编码在里面么？  还是怎么样？ 那assets打包部分，我们拿到了对比，知道哪些文件增加，修改，那应该如何将这些信息集成到bundle里面呢？

**Comment by cnsnake11** [comment]
我们没有用codepush，是自己实现的升级系统。
app拿到增量包之后，直接将增量包中的asserts文件夹和文件覆盖到本地版本的asserts文件夹上，就得到了最新版本的asserts文件夹。
