### ISSUE TITLE
对react-native-tabbar的使用过程中的一些疑问(父组件setState不会触发render)?!

### ISSUE THREAD

**Issue by naivehhr** [cnsnake11/blog#7]
不知道楼主是否用过react-native-tabbar组件，现有些疑问，特此请教(如果是react-native-tabbar的问题本应提到react-native-tabbar的问题列表中，但怀疑也许是自己理解不够....)。
组件中部分方法：

```
constructor(props, context) {
    super(props, context);
    this.state = {
               name: '小怪兽'
    }
 }
componentDidMount() {
    setTimeout(() => {
      this.setState({name: '凹凸曼'})
    },500)
  }

父组件：
/** 使用react-native-tabbar */
render() {
    return (
      <Tabbar ref="myTabbar" barColor={'rgb(0, 0, 0)'}>
        <Tab name="FirstTab">
          <IconWithBar label='FirstTab' onInactiveColor={'white'} onActiveColor={'red'} type={glypy.Match} ontype={glypy.MatchOn} from={'tabbaricon'}/>
          <RawContent>
          <View>
          <B  {...this.state}/>
          </View>
          </RawContent>
        </Tab>
      </Tabbar>
    );
  }
/** 不使用react-native-tabbar*/
render() {
    return (
      <View>
          <B {...this.state}/>
          </View>
    );
  }

/** B组件*/
render() {
    return (
      <View>
      <Text>Component BBBB: {this.props.name}</Text>
      </View>
    );
  }
```

在使用react-native-tabbar 的情况中，B组件中的‘<Text>Component BBBB: {this.props.name}</Text>’中内容不会发生改变，而不使用react-native-tabbar B中内容是可以改变的。现能怀疑的问题就是react-native-tabbar组件内部的某些实现过程阻断了state改变重新render的过程。所以想请教下，什么情况下会类似于这种无法更新的情况。

**Comment by cnsnake11** [comment]
在页面state发生变化的时候，某个组件是否发生变化，是和这个组件的shouldComponentUpdate方法的返回值有关的，具体你可以看看react的文档。http://www.reactjs.cn/react/docs/component-specs.html#-shouldcomponentupdate

Tabbar我没有用到过，不过你说的这个现象应该是和Tabbar的实现原理有关，肯定不是你代码的问题。

总之，rn中那些基本的组件肯定会随着state的改变而触发render，比如像view text image scrollview等，其它的组件是否随着state的改变而触发render，是要看这个组件的实现原理的。

**Comment by naivehhr** [comment]
多谢回复哈。经测试使用Tabbar其子组件还都没有触发componentWillReceiveProps，应该表明其并没有向下传递props吧~~有时间扒扒源码去，争取自己写一个出来:-)
